### ISSUE TITLE
war is being created before the merge is done.

### ISSUE THREAD

**Issue by scaddenp** [MehdiBekioui/merge-maven-plugin#3]
Hmm, maven-war-plugin, is creating the war BEFORE merge-maven-plugin runs. Looks a phasing issue. Is this something wrong with my POM?

**Comment by MehdiBekioui** [comment]
The default merge-maven-plugin phase is generate-resources.
The maven-war-plugin is used with the compile or package phases.
If you did not change the merge-maven-plugin phase it should be worked.
Could you post your pom.xml please?

**Comment by scaddenp** [comment]
Thanks very much for the prompt reply. I think I have made a dumb error. Let me check.

**Comment by scaddenp** [comment]
okay, I was use two different merge-maven-plugins in the one pom. (experimenting with both). Duh. However, if I do a build without clean, it complains that file already exists (obviously from the previous build), which is somewhat inconvenient. When developing in netbeans, project can be set to automatically build and redeploy, which is very convenient when only modifying js or html. Preferred behaviour would be to overwrite existing target.

**Comment by MehdiBekioui** [comment]
It is possible to add a configuration property to allow overwrite by merge.

**Comment by scaddenp** [comment]
That would be good!
________________________________

**Comment by MehdiBekioui** [comment]
You could use the 1.2.0 version to override existing file now.

**Comment by scaddenp** [comment]
Great! Thanks very much
