### ISSUE TITLE
Cannot find 'override' in class com.bekioui.maven.plugin.merge.Merge

### ISSUE THREAD

**Issue by zeppelinux** [MehdiBekioui/merge-maven-plugin#4]
Failed to execute goal com.bekioui.maven.plugin:merge-maven-plugin:1.1.0:merge (merge-files) on project michelin-naclaims: Unable to parse configuration of mojo com.bekioui.maven.plugin:merge-maven-plugin:1.1.0:merge for parameter override: Cannot find 'override' in class com.bekioui.maven.plugin.merge.Merge

**Comment by MehdiBekioui** [comment]
Hi, you have to use the new version 1.2.0 to define the override tag.
